[package]
name = "template-benchmarks-rs"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
askama = { git = "https://github.com/djc/askama" }
criterion = "0.2"
handlebars = { git = "https://github.com/sunng87/handlebars-rust" }
horrorshow = { git = "https://github.com/Stebalien/horrorshow-rs" }
liquid = { git = "https://github.com/cobalt-org/liquid-rust" }
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
tera = { git = "https://github.com/Keats/tera" }
fomat-macros = { git = "https://github.com/krdln/fomat-macros" }

[[bench]]
name = "all"
harness = false
